### ISSUE TITLE
Investigate why lizzy traffic is failing

### ISSUE THREAD

**Issue by jmcs** [zalando/lizzy#24]
SEE:

    Nov 19 13:25:28 ip-172-31-168-128 docker/2de453ab1363[840]: 
    {"time": "2015-11-19T13:25:28.810169", 
     "logger": "lizzy.senza", 
     "log_level": "ERROR", 
     "function": "senza_wrapper._execute", 
     "line": 89, "msg": "Error executing command.", 
     "command.output": "Calculating new weights.. OK\n[{\"compensation\": null, \"current\": null, \"delta\": -100.0, \"identifier\": \"lizzy-bus-133T20151119105600\", \"new_weight%\": 0.0, \"old_weight%\": 100.0, \"stack_name\": \"lizzy-bus\", \"version\": \"133T20151119105600\"}, {\"compensation\": null, \"current\": null, \"delta\": null, \"identifier\": \"lizzy-bus-135T20151119123522\", \"new_weight%\": 0.0, \"old_weight%\": 0.0, \"stack_name\": \"lizzy-bus\", \"version\": \"135T20151119123522\"}, {\"compensation\": null, \"current\": \"<\", \"delta\": 100.0, \"identifier\": \"lizzy-bus-135T20151119131936\", \"new_weight%\": 100.0, \"old_weight%\": 0.0, \"stack_name\": \"lizzy-bus\", \"version\": \"135T20151119131936\"}]\nTraceback (most recent call last):\n  File \"/usr/local/bin/senza\", line 11, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.4/dist-packages/senza/cli.py\", line 1360, in main\n    handle_exceptions(cli)()\n  File \"/usr/local/lib/python3.4/dist-packages/senza/cli.py\", line 248, in wrapper\n    func()\n  File \"/usr/local/lib/python3.4/dist-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python3.4/dist-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/usr/local/lib/python3.4/dist-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/local/lib/python3.4/dist-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/local/lib/python3.4/dist-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/usr/local/lib/python3.4/dist-packages/senza/cli.py\", line 1043, in traffic\n    change_version_traffic(ref, percentage, region)\n  File \"/usr/local/lib/python3.4/dist-packages/senza/traffic.py\", line 374, in change_version_traffic\n    inform_sns(arns, message, region)\n  File \"/usr/local/lib/python3.4/dist-packages/senza/traffic.py\", line 381, in inform_sns\n    sns = boto3.client('sns')\n  File \"/usr/local/lib/python3.4/dist-packages/boto3/__init__.py\", line 79, in client\n    return _get_default_session().client(*args, **kwargs)\n  File \"/usr/local/lib/python3.4/dist-packages/boto3/session.py\", line 199, in client\n    aws_session_token=aws_session_token, config=config)\n  File \"/usr/local/lib/python3.4/dist-packages/botocore/session.py\", line 762, in create_client\n    client_config=config, api_version=api_version)\n  File \"/usr/local/lib/python3.4/dist-packages/botocore/client.py\", line 62, in create_client\n    verify, credentials, scoped_config, client_config)\n  File \"/usr/local/lib/python3.4/dist-packages/botocore/client.py\", line 227, in _get_client_args\n    endpoint_url)\n  File \"/usr/local/lib/python3.4/dist-packages/botocore/client.py\", line 117, in _get_signature_version_and_region\n    service_model.endpoint_prefix, region_name, scheme=scheme)\n  File \"/usr/local/lib/python3.4/dist-packages/botocore/regions.py\", line 70, in construct_endpoint\n    raise NoRegionError()\nbotocore.exceptions.NoRegionError: You must specify a region.", 
     "command": "senza traffic --region eu-west-1 -o json lizzy-bus 135T20151119131936 100"}

**Comment by jmcs** [comment]
Output:

    Calculating new weights.. OK
    [{"compensation": null, "current": null, "delta": -100.0, "identifier": "lizzy-bus-133T20151119105600", "new_weight%": 0.0, "old_weight%": 100.0, "stack_name": "lizzy-bus", "version": "133T20151119105600"}, {"compensation": null, "current": null, "delta": null, "identifier": "lizzy-bus-135T20151119123522", "new_weight%": 0.0, "old_weight%": 0.0, "stack_name": "lizzy-bus", "version": "135T20151119123522"}, {"compensation": null, "current": "<", "delta": 100.0, "identifier": "lizzy-bus-135T20151119131936", "new_weight%": 100.0, "old_weight%": 0.0, "stack_name": "lizzy-bus", "version": "135T20151119131936"}]
    Traceback (most recent call last):
      File "/usr/local/bin/senza", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 1360, in main
        handle_exceptions(cli)()
      File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 248, in wrapper
        func()
      File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 700, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 680, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1027, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 873, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 508, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 1043, in traffic
        change_version_traffic(ref, percentage, region)
      File "/usr/local/lib/python3.4/dist-packages/senza/traffic.py", line 374, in change_version_traffic
        inform_sns(arns, message, region)
      File "/usr/local/lib/python3.4/dist-packages/senza/traffic.py", line 381, in inform_sns
        sns = boto3.client('sns')
      File "/usr/local/lib/python3.4/dist-packages/boto3/__init__.py", line 79, in client
        return _get_default_session().client(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/boto3/session.py", line 199, in client
        aws_session_token=aws_session_token, config=config)
      File "/usr/local/lib/python3.4/dist-packages/botocore/session.py", line 762, in create_client
        client_config=config, api_version=api_version)
      File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 62, in create_client
        verify, credentials, scoped_config, client_config)
      File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 227, in _get_client_args
        endpoint_url)
      File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 117, in _get_signature_version_and_region
        service_model.endpoint_prefix, region_name, scheme=scheme)
      File "/usr/local/lib/python3.4/dist-packages/botocore/regions.py", line 70, in construct_endpoint
        raise NoRegionError()
    botocore.exceptions.NoRegionError: You must specify a region.

**Comment by jmcs** [comment]
Fixed by  zalando-stups/senza#147
